In [7]:
import pandas as pd

In [9]:
df = pd.read_csv(r"C:\Users\ADMIN\Downloads\spotify_millsongdata.csv.zip")

In [10]:
df.head(5)

,artist,song,link,text
0,ABBA,Ahe's My Kind Of Girl,/a/abba/ahes+my+kind+of+girl_20598417.html,"Look at her face, it's a wonderful face \r\nA..."
1,ABBA,"Andante, Andante",/a/abba/andante+andante_20002708.html,"Take it easy with me, please \r\nTouch me gen..."
2,ABBA,As Good As New,/a/abba/as+good+as+new_20003033.html,I'll never know why I had to go \r\nWhy I had...
3,ABBA,Bang,/a/abba/bang_20598415.html,Making somebody happy is a question of give an...
4,ABBA,Bang-A-Boomerang,/a/abba/bang+a+boomerang_20002668.html,Making somebody happy is a question of give an...

In [11]:
df.tail(5)

,artist,song,link,text
57645,Ziggy Marley,Good Old Days,/z/ziggy+marley/good+old+days_10198588.html,Irie days come on play \r\nLet the angels fly...
57646,Ziggy Marley,Hand To Mouth,/z/ziggy+marley/hand+to+mouth_20531167.html,Power to the workers \r\nMore power \r\nPowe...
57647,Zwan,Come With Me,/z/zwan/come+with+me_20148981.html,all you need \r\nis something i'll believe \...
57648,Zwan,Desire,/z/zwan/desire_20148986.html,northern star \r\nam i frightened \r\nwhere ...
57649,Zwan,Heartsong,/z/zwan/heartsong_20148991.html,come in \r\nmake yourself at home \r\ni'm a ...

In [12]:
df.shape

(57650, 4)

In [13]:
df.isnull().sum()

artist    0
song      0
link      0
text      0
dtype: int64

In [14]:
df =df.sample(5000).drop('link', axis=1).reset_index(drop=True)

In [15]:

df.head(10)

,artist,song,text
0,Lynyrd Skynyrd,Outta Hell In My Dodge,"Five AM in the mornin', whiskey still runnin' ..."
1,Howard Jones,Roll Right Up,Will the moon keep shining on \r\nCan you sto...
2,Harry Belafonte,Zombie Jamboree (Back To Back),Lyrics: \r\nIt was a Zombie Jamboree \r\nToo...
3,Doobie Brothers,Feelin' Down Farther,"Well, the sun is shinin? a new day is here \r..."
4,Rush,Red Tide,Nature has some new plague \r\nTo run in our ...
5,Bee Gees,Cucumber Castle,"There were the trees, see the grass, a thing g..."
6,Peter Gabriel,This Is The Picture,Excellent birds \r\n \r\nFlying birds \r\nE...
7,Outkast,Bowtie,[Chorus] \r\nCrocodile on my feet \r\nFox fu...
8,Ofra Haza,Da'ale Da'ale,YAH YAH HABIBI WEN ISALAM?! \r\nGULI KALAM......
9,Tim McGraw,Some Things Never Change,"After all this time, I still miss you everyday..."

In [16]:
df['text'][0]

"Five AM in the mornin', whiskey still runnin' through my head  \r\nI could get out of bed and maybe I'll just have another cigarette  \r\nAs long as I can remember seems all I've ever done is work  \r\nThe boss is a jerk and I ain't payin' the rent  \r\nSpent my whole life shovelin' dirt  \r\n  \r\n[Chorus]  \r\nI'm gonna get outta hell in my dodge  \r\nCan't take this anymore  \r\nGonna go downtown pick up my girl  \r\nThere ain't nothin' worth waitin' for  \r\nTake the road less traveled  \r\nSpend my life behind the wheel  \r\nGonna get outta hell in my dodge  \r\nFreedom made out of steel  \r\n  \r\nThere's a knock on the door from the sheriff  \r\nAskin' me where I was last night  \r\nSeems somebody lookin' a lot like me  \r\nHad takin' up with his wife  \r\nHe said son if I ever catch him  \r\nThere's gonna be some hell to pay  \r\nHe'll be gone for good if I see him again  \r\n'cause I just might blow him away  \r\n  \r\n[Chorus]  \r\n  \r\nWhat's a poor man supposed to do  \r\nStuck in the middle and trapped by the blues  \r\nBaby, I'm sick of these blues  \r\n  \r\nI'm gonna get outta hell in my dodge  \r\nCan't take this anymore  \r\nGonna go downtown pick up my girl  \r\nThere ain't nothin' worth waitin' for  \r\nWell I don't care if I'm wrong or right  \r\nGotta split this town tonight  \r\nGonna get outta hell in my dodge  \r\nLive my life behind the wheel  \r\nI'm gonna get outta hell in my dodge  \r\nMy freedom made out of steel\r\n\r\n"

In [17]:
# df = df.sample(5000)

In [18]:
df.shape

(5000, 3)

In [21]:
df['text'] = df['text'].str.lower().replace(r'^\w\s', ' ').replace(r'\n', ' ', regex = True)

In [ ]:
import nltk
nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml

In [ ]:
from nltk.corpus import brown
brown.words()

In [ ]:
nltk.set_proxy('http://proxy.example.com:3128', ('USERNAME', 'PASSWORD'))
nltk.download()

In [ ]:
import nltk
from nltk.stem.porter import PorterStemmer
stemmer = PorterStemmer()

def tokenization(txt):
    tokens = nltk.word_tokenize(txt)
    stemming = [stemmer.stem(w) for w in tokens]
    return " ".join(stemming)

In [ ]:
df['text'] = df['text'].apply(lambda x: tokenization(x))

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
tfidvector = TfidfVectorizer(analyzer='word',stop_words='english')
matrix = tfidvector.fit_transform(df['text'])
similarity = cosine_similarity(matrix)

In [ ]:
similarity[0]

In [ ]:
df[df['song'] == 'Crying Over You']

In [ ]:
def recommendation(song_df):
    idx = df[df['song'] == song_df].index[0]
    distances = sorted(list(enumerate(similarity[idx])),reverse=True,key=lambda x:x[1])
    
    songs = []
    for m_id in distances[1:21]:
        songs.append(df.iloc[m_id[0]].song)
        
    return songs

In [ ]:
recommendation('Crying Over You')

In [ ]:
import pickle
pickle.dump(similarity,open('similarity.pkl','wb'))
pickle.dump(df,open('df.pkl','wb'))